### ISSUE TITLE
There is an error in the document: Defining Workload Types | Composition

### ISSUE THREAD

**Issue by kinnylee** [oam-dev/kubevela#1113] opened 2021-03-01 06:42 UTC
**Describe the bug**
There is an error in the document：https://kubevela.io/#/en/cue/workload-type?id=composition
It should be WorkloadDefinition.spec.extension.template, not WorkloadDefinition.spec.template?

**To Reproduce**
1. Go to https://kubevela.io/#/en/cue/workload-type?id=composition
2. save WorkloadDefinition named webserver to workloaddefinition-webserver.yaml file
3. run kubectl apply -f workloaddefinition-webserver.yaml
4. See error: error validating "workloaddefinition-webserver.yaml": error validating data: ValidationError(WorkloadDefinition.spec): unknown field "template" in dev.oam.core.v1alpha2.WorkloadDefinition.spec; if you choose to ignore these errors, turn validation off with --validate=false

**Expected behavior**
webserver workloaddefinition create successfully

**Screenshots**

**Cluster information**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by yangsoon** [comment] 2021-03-01 13:47
This problem should be caused by the low version of vela. Please try again after recompiling a new **vela** executable file under the latest master branch.

**Comment by yangsoon** [comment] 2021-03-01 14:16
Please try to use helm reinstall KubeVela Controller, while please use 
`helm install --create-namespace -n vela-system kubevela kubevela/vela-core --version 0.4.0-rc-master`
command

**Comment by wonderflow** [comment] 2021-05-06 09:58
it's fixed now

**Closed** 2021-05-06 09:58 UTC
