### ISSUE TITLE
vela up -f https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml

### ISSUE THREAD

**Issue by zhangb191** [oam-dev/kubevela#941] opened 2021-01-26 09:09 UTC
Parsing vela appfile ...
Error: Get "https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml": dial tcp 0.0.0.0:443: connect: connection refused

**Comment by wonderflow** [comment] 2021-01-26 09:12
can you try 

```
curl https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml
```

Make sure you're not blocked by GFW

**Comment by zhangb191** [comment] 2021-01-27 00:59
> 你能试一下吗
> 
> ```
> curl https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml
> ```
> 
> 确保您没有被GFW阻止

curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

**Comment by wonderflow** [comment] 2021-01-27 12:08
I can't reproduce it, closing, feel free to reopen if it's still happening.

**Closed by wonderflow** 2021-01-27 12:08 UTC
