### ISSUE TITLE
[BUG] There were capabilities updated and deleted when installing vela in a clean clsuter

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#536] opened 2020-11-09 02:08 UTC
In a newly deployed Kubernetes Kind cluster, there were some capabilities updated and deleted when `vela install`.
```
vela install
- Installing Vela Core Chart:
created namespace vela-system
install chart vela-core, version 0.1.0, desc : A Helm chart for Kube Vela core, contains 34 file
Successfully installed the chart, status: deployed, last deployed time = 2020-11-09 10:04:37.206566 +0800 CST m=+7.170531404
Synchronizing capabilities from cluster⌛ ...
Sync capabilities successfully ✅ Add(2) Update(5) Delete(3)
TYPE                              	CATEGORY	DESCRIPTION
+worker                           	workload	Backend worker without ports exposed
+autoscale                        	trait   	Automatically scale workloads
*task                             	workload	One-time task/job
*webservice                       	workload	Long running service with network routes
*metric                           	trait   	Add metric monitoring for workload
*route                            	trait   	Add a route for workload
*scaler                           	trait   	Scale replica for workload
-backend                          	workload	Backend worker without ports exposed
-podspecworkloads.standard.oam.dev	workload	description not defined
-manualscalertraits.core.oam.dev  	trait   	description not defined
- Finished successfully.
```

Expected: Only new capabilities added.

**Comment by captainroy-hy** [comment] 2020-11-09 02:45
I try to run latest "vela install" in a newly created kind cluster and with **a clean local vela capability folder**.
And here is the result.
```shell
Sync capabilities successfully ✅ Add(7) Update(0) Delete(0)
TYPE       	CATEGORY	DESCRIPTION
+task      	workload	One-time task/job
+webservice	workload	Long running service with network routes
+worker    	workload	Backend worker without ports exposed
+autoscale 	trait   	Automatically scale workloads
+metric    	trait   	Add metric monitoring for workload
+route     	trait   	Add a route for workload
+scaler    	trait   	Scale replica for workload
```
Then delete the cluster and re-create a new one, and run `vela install` again.
```shell
Synchronizing capabilities from cluster⌛ ...
Sync capabilities successfully ✅ (no changes)
TYPE      	CATEGORY	DESCRIPTION
task      	workload	One-time task/job
webservice	workload	Long running service with network routes
worker    	workload	Backend worker without ports exposed
autoscale 	trait   	Automatically scale workloads
metric    	trait   	Add metric monitoring for workload
route     	trait   	Add a route for workload
scaler    	trait   	Scale replica for workload
```
As for the deleted/updated ones in your problem statement, maybe it's caused by a used local vela capability folder, e.g., already containing inconsistent capabilities against vela built-in ones.

**Comment by wonderflow** [comment] 2020-11-16 08:10
I didn't reproduce this issue, closing. Feel free to reopen if it happens to you again.

**Closed by wonderflow** 2020-11-16 08:10 UTC
Labels: bug
