### ISSUE TITLE
webserver workloaddefinition not work

### ISSUE THREAD

**Issue by kinnylee** [oam-dev/kubevela#1116] opened 2021-03-01 08:39 UTC
**Describe the bug**
kubevela engine can not render application to applicationconfiguration when appfile has a webserver workload.

**To Reproduce**
1. Go to 'https://kubevela.io/#/en/cue/workload-type?id=composition'
2. Save the WorkloadDefinition with type webserver to file workload-definition-webserver.yaml
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webserver
  annotations:
    definition.oam.dev/description: "webserver is a combo of Deployment + Service"
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          spec: {
              selector: matchLabels: {
                  "app.oam.dev/component": context.name
              }
              template: {
                  metadata: labels: {
                      "app.oam.dev/component": context.name
                  }
                  spec: {
                      containers: [{
                          name:  context.name
                          image: parameter.image
      
                          if parameter["cmd"] != _|_ {
                              command: parameter.cmd
                          }
      
                          if parameter["env"] != _|_ {
                              env: parameter.env
                          }
      
                          if context["config"] != _|_ {
                              env: context.config
                          }
      
                          ports: [{
                              containerPort: parameter.port
                          }]
      
                          if parameter["cpu"] != _|_ {
                              resources: {
                                  limits:
                                      cpu: parameter.cpu
                                  requests:
                                      cpu: parameter.cpu
                              }
                          }
                      }]
                  }
              }
          }
      }
      // an extra template
      outputs: service: {
          apiVersion: "v1"
          kind:       "Service"
          spec: {
              selector: {
                  "app.oam.dev/component": context.name
              }
              ports: [
                  {
                      port:       parameter.port
                      targetPort: parameter.port
                  },
              ]
          }
      }
      parameter: {
          image: string
          cmd?: [...string]
          port: *80 | int
          env?: [...{
              name:   string
              value?: string
              valueFrom?: {
                  secretKeyRef: {
                      name: string
                      key:  string
                  }
              }
          }]
          cpu?: string
      }
```
3. Run `kubectl apply -f workload-definition-webserver.yaml`
4. Run `vela workloads` show the webserver that we has registed
5. Add vela.yaml file, content is:
```yaml
name: bookinfo
services:
  productpage:
    type: webserver
    image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
    port: 9080
  details:
    type: webserver
    image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
    port: 9080
  ratings:
    type: webserver
    image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
    port: 9080
  reviews:
    type: webserver
    image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
    port: 9080
```
6. Run `vela up -f vela.yaml`
7. Run `vela ls`, see show nothing; `kubectl get application.core.oam.dev -A` show successfully, but `kubectl get applicationconfiguration.core.oam.dev -A` also show nothing

**Expected behavior**
- `vela ls` can show the app info
- `kubectl get applicationconfiguration` can show app config info

**Screenshots**
![image](https://user-images.githubusercontent.com/10666512/109474147-2a270d80-7aaf-11eb-87da-3f9ceee3b0e4.png)
![image](https://user-images.githubusercontent.com/10666512/109474262-4c209000-7aaf-11eb-8ef0-8f8900821cd4.png)
![image](https://user-images.githubusercontent.com/10666512/109475064-36f83100-7ab0-11eb-8ebc-63bc156ba643.png)

**Cluster information**
[root@middleware-1810-02 bookinfo]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

[root@middleware-1810-02 bookinfo]# vela version
Version: refs/tags/v0.3.2
GitRevision: git-18f184d
GolangVersion: go1.14.14

**Additional context**

**Comment by yangsoon** [comment] 2021-03-01 13:48
This problem should be caused by the low version of vela. Please try again after recompiling a new vela executable file under the latest master branch.

**Comment by just-do1** [comment] 2021-03-02 01:35
According to your description, v0.3.3 performs normally

```shell
[root@n215 webserver]# vela up
Parsing vela appfile ...
Load Template ...

Rendering configs for service (details)...

Rendering configs for service (productpage)...

Rendering configs for service (ratings)...

Rendering configs for service (reviews)...
Writing deploy config to (.vela/deploy.yaml)

Applying application ...
Checking if app has been deployed...
App has not been deployed, creating a new deployment...
✅ App has been deployed 🚀🚀🚀
    Port forward: vela port-forward bookinfo
             SSH: vela exec bookinfo
         Logging: vela logs bookinfo
      App status: vela status bookinfo
  Service status: vela status bookinfo --svc details
  Service status: vela status bookinfo --svc productpage
  Service status: vela status bookinfo --svc ratings
  Service status: vela status bookinfo --svc reviews

[root@n215 webserver]# vela ls
list application err name is required
SERVICE    	APP     	TYPE	TRAITS	STATUS  	CREATED-TIME
details    	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST
productpage	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST
ratings    	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST
reviews    	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST

[root@n215 webserver]# kubectl get application -A
NAMESPACE   NAME       AGE
default     bookinfo   17s

[root@n215 webserver]# vela version
Version: refs/tags/v0.3.3
GitRevision: git-f6d2e76
GolangVersion: go1.14.15
```

**Comment by just-do1** [comment] 2021-03-02 02:25
In vela v0.3.2, The error is that. 
```shell
$ kubectl logs -f -n vela-system kubevela-vela-core-6c64c6dd8f-rp54k

2021-03-02T01:46:50.265Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validating-core-oam-dev-v1alpha2-applicationconfigurations", "UID": "9e3e3055-b91a-4e2d-b083-1627f2861bb4", "kind": "core.oam.dev/v1alpha2, Kind=ApplicationConfiguration", "resource": {"group":"core.oam.dev","version":"v1alpha2","resource":"applicationconfigurations"}}
I0302 01:46:50.265525       1 validating_handler.go:99] failed init appConfig before validation  name: bookinfo errMsg: cannot get trait definition in component "productpage": TraitDefinition.core.oam.dev "AuxiliaryWorkload" not found
2021-03-02T01:46:50.265Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validating-core-oam-dev-v1alpha2-applicationconfigurations", "code": 403, "reason": "cannot get trait definition in component \"productpage\": TraitDefinition.core.oam.dev \"AuxiliaryWorkload\" not found", "UID": "9e3e3055-b91a-4e2d-b083-1627f2861bb4", "allowed": false}
2021-03-02T01:46:50.266Z	ERROR	Application	[Handle apply]	{"application": "default/bookinfo", "error": "admission webhook \"validating.core.oam.dev.v1alpha2.applicationconfigurations\" denied the request: cannot get trait definition in component \"productpage\": TraitDefinition.core.oam.dev \"AuxiliaryWorkload\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/application.(*Reconciler).Reconcile
	/workspace/pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
```

In v0.3.2

https://github.com/oam-dev/kubevela/blob/18f184d57c6261515033a509ae76a4f70752fd56/pkg/controller/core.oam.dev/v1alpha2/application/apply.go#L60-L74

In the latest master

https://github.com/oam-dev/kubevela/blob/a8337921bc13d9efee8fbfa28c27af5045203f95/pkg/controller/core.oam.dev/v1alpha2/application/apply.go#L71-L117

**Comment by just-do1** [comment] 2021-03-02 03:27
In Vela v0.3.2, I saw the error is:

```shell
$ kubectl logs -f -n vela-system kubevela-vela-core-6c64c6dd8f-rp54k

2021-03-02T02:58:01.597Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutating-core-oam-dev-v1alpha2-applicationconfigurations", "code": 200, "reason": "", "UID": "c735ac0c-5e92-449f-abc0-d07a3960a796", "allowed": true}
2021-03-02T02:58:01.600Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validating-core-oam-dev-v1alpha2-applicationconfigurations", "UID": "23ac663e-6f9f-422e-98b9-7bfc66222de7", "kind": "core.oam.dev/v1alpha2, Kind=ApplicationConfiguration", "resource": {"group":"core.oam.dev","version":"v1alpha2","resource":"applicationconfigurations"}}
2021-03-02T02:58:01.600Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validating-core-oam-dev-v1alpha2-applicationconfigurations", "code": 403, "reason": "cannot get trait definition in component \"details\": TraitDefinition.core.oam.dev \"AuxiliaryWorkload\" not found", "UID": "23ac663e-6f9f-422e-98b9-7bfc66222de7", "allowed": false}
I0302 02:58:01.600869       1 validating_handler.go:99] failed init appConfig before validation  name: bookinfo errMsg: cannot get trait definition in component "details": TraitDefinition.core.oam.dev "AuxiliaryWorkload" not found
2021-03-02T02:58:01.601Z	ERROR	Application	[Handle apply]	{"application": "default/bookinfo", "error": "admission webhook \"validating.core.oam.dev.v1alpha2.applicationconfigurations\" denied the request: cannot get trait definition in component \"details\": TraitDefinition.core.oam.dev \"AuxiliaryWorkload\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/application.(*Reconciler).Reconcile
	/workspace/pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
```

I found this  in vela v0.3.2:

https://github.com/oam-dev/kubevela/blob/18f184d57c6261515033a509ae76a4f70752fd56/pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler.go#L70-L140


But in the latest master, the function `ValidateTraitObjectFn` is remove.

This bug is because of this?

**Comment by kinnylee** [comment] 2021-03-03 07:21
> According to your description, v0.3.3 performs normally
> 
> ```shell
> [root@n215 webserver]# vela up
> Parsing vela appfile ...
> Load Template ...
> 
> Rendering configs for service (details)...
> 
> Rendering configs for service (productpage)...
> 
> Rendering configs for service (ratings)...
> 
> Rendering configs for service (reviews)...
> Writing deploy config to (.vela/deploy.yaml)
> 
> Applying application ...
> Checking if app has been deployed...
> App has not been deployed, creating a new deployment...
> ✅ App has been deployed 🚀🚀🚀
>     Port forward: vela port-forward bookinfo
>              SSH: vela exec bookinfo
>          Logging: vela logs bookinfo
>       App status: vela status bookinfo
>   Service status: vela status bookinfo --svc details
>   Service status: vela status bookinfo --svc productpage
>   Service status: vela status bookinfo --svc ratings
>   Service status: vela status bookinfo --svc reviews
> 
> [root@n215 webserver]# vela ls
> list application err name is required
> SERVICE    	APP     	TYPE	TRAITS	STATUS  	CREATED-TIME
> details    	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST
> productpage	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST
> ratings    	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST
> reviews    	bookinfo	    	      	Deployed	2021-03-02 09:30:39 +0800 CST
> 
> [root@n215 webserver]# kubectl get application -A
> NAMESPACE   NAME       AGE
> default     bookinfo   17s
> 
> [root@n215 webserver]# vela version
> Version: refs/tags/v0.3.3
> GitRevision: git-f6d2e76
> GolangVersion: go1.14.15
> ```

thanks！I upgrade KubeVela Controller to v0.3.3,  performs normally。
There is, in addition, CUE syntax errors can cause rendering Application to ApplicationConfiguration failures， can find problems by looking at the vela-core pod logs.

**Comment by wonderflow** [comment] 2021-03-04 04:00
Thanks @kinnylee @just-do1  closing

**Closed by wonderflow** 2021-03-04 04:00 UTC
