### ISSUE TITLE
Flux cannot start running

### ISSUE THREAD

**Issue by sunny0826** [oam-dev/kubevela#1381] opened 2021-03-31 08:45 UTC
**Describe the bug**

After installing `Flux` successfully, I found that it was not working properly and was restarting constantly.

**To Reproduce**

install flux
```shell
$ helm install --create-namespace -n flux-system helm-flux http://oam.dev/catalog/helm-flux2-0.1.0.tgz
```

check status
```shell
$ k get pod -n  flux-system
NAME                                READY   STATUS             RESTARTS   AGE
helm-controller-64df447b8d-xfrnk    0/1     CrashLoopBackOff   11         22m
source-controller-b98fb8898-rldg6   0/1     CrashLoopBackOff   11         22m
```

**Screenshots**

![image](https://user-images.githubusercontent.com/24563928/113116592-2b7b5f80-9240-11eb-8c14-db43b37186b8.png)

**Cluster information**

- ACK v1.18.8-aliyun.1

**pod log**

`source-controller` log
```shell
$ k logs source-controller-b98fb8898-rldg6
{"level":"info","ts":"2021-03-31T08:41:18.629Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2021-03-31T08:41:18.629Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:18.630Z","logger":"setup","msg":"starting manager"}
I0331 08:41:18.630532       6 leaderelection.go:243] attempting to acquire leader lease flux-system/305740c0.fluxcd.io...
{"level":"info","ts":"2021-03-31T08:41:18.730Z","msg":"starting metrics server","path":"/metrics"}
I0331 08:41:34.887539       6 leaderelection.go:253] successfully acquired lease flux-system/305740c0.fluxcd.io
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"setup","msg":"starting file server"}
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"controller.helmrepository","msg":"Starting EventSource","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmRepository","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"controller.helmchart","msg":"Starting EventSource","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"controller.helmrepository","msg":"Starting Controller","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmRepository"}
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"controller.bucket","msg":"Starting EventSource","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"Bucket","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"controller.helmrepository","msg":"Starting workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmRepository","worker count":2}
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"controller.helmchart","msg":"Starting EventSource","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:34.887Z","logger":"controller.gitrepository","msg":"Starting EventSource","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:34.888Z","logger":"controller.helmchart","msg":"Starting EventSource","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:34.988Z","logger":"controller.helmchart","msg":"Starting EventSource","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:34.988Z","logger":"controller.helmchart","msg":"Starting Controller","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart"}
{"level":"info","ts":"2021-03-31T08:41:34.988Z","logger":"controller.bucket","msg":"Starting Controller","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"Bucket"}
{"level":"info","ts":"2021-03-31T08:41:34.988Z","logger":"controller.gitrepository","msg":"Starting Controller","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository"}
{"level":"info","ts":"2021-03-31T08:41:34.988Z","logger":"controller.gitrepository","msg":"Starting workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","worker count":2}
{"level":"info","ts":"2021-03-31T08:41:34.988Z","logger":"controller.helmchart","msg":"Starting workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","worker count":2}
{"level":"info","ts":"2021-03-31T08:41:34.988Z","logger":"controller.bucket","msg":"Starting workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"Bucket","worker count":2}
{"level":"info","ts":"2021-03-31T08:41:47.982Z","logger":"controller.helmrepository","msg":"Stopping workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmRepository"}
{"level":"info","ts":"2021-03-31T08:41:47.982Z","logger":"controller.gitrepository","msg":"Stopping workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository"}
{"level":"info","ts":"2021-03-31T08:41:47.982Z","logger":"controller.helmchart","msg":"Stopping workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart"}
{"level":"info","ts":"2021-03-31T08:41:47.982Z","logger":"controller.bucket","msg":"Stopping workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"Bucket"}
```

`helm-controller` log
```shell
$ k logs helm-controller-64df447b8d-xfrnk
{"level":"info","ts":"2021-03-31T08:41:30.395Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2021-03-31T08:41:30.396Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:30.396Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:30.396Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:30.396Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-03-31T08:41:30.396Z","logger":"setup","msg":"starting manager"}
I0331 08:41:30.396355       6 leaderelection.go:243] attempting to acquire leader lease flux-system/5b6ca942.fluxcd.io...
{"level":"info","ts":"2021-03-31T08:41:30.396Z","msg":"starting metrics server","path":"/metrics"}
I0331 08:41:46.787819       6 leaderelection.go:253] successfully acquired lease flux-system/5b6ca942.fluxcd.io
{"level":"info","ts":"2021-03-31T08:41:46.787Z","logger":"controller.helmrelease","msg":"Starting EventSource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:46.788Z","logger":"controller.helmrelease","msg":"Starting EventSource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-03-31T08:41:46.888Z","logger":"controller.helmrelease","msg":"Starting Controller","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease"}
{"level":"info","ts":"2021-03-31T08:41:46.888Z","logger":"controller.helmrelease","msg":"Starting workers","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","worker count":4}
{"level":"info","ts":"2021-03-31T08:41:59.762Z","logger":"controller.helmrelease","msg":"Stopping workers","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease"}
```

**Comment by captainroy-hy** [comment] 2021-04-01 02:21
Hi @sunny0826 I cannot reproduce the issue on my local env(kind 1.16,1.18,1.19) and ack 1.16. And I have no ack 1.18 env to test...
So could you please enable "--log-level=debug" flag of helm-controller as below? Then maybe we can get better insight into the problem.
```shell
kubectl patch deployment helm-controller -n flux-system --patch "spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --watch-all-namespaces
            - --log-level=debug
            - --log-encoding=json
            - --enable-leader-election"
```

**Comment by sunny0826** [comment] 2021-04-01 02:57
`helm-controller` yaml

```shell
k get deployment helm-controller -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: helm-flux
    meta.helm.sh/release-namespace: flux-system
  creationTimestamp: "2021-04-01T02:50:18Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/managed-by: Helm
    control-plane: controller
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:control-plane: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:prometheus.io/port: {}
              f:prometheus.io/scrape: {}
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"manager"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"RUNTIME_NAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8080,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":9440,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:readOnlyRootFilesystem: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/tmp"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"temp"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
    manager: Go-http-client
    operation: Update
    time: "2021-04-01T02:50:18Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:unavailableReplicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-01T02:54:09Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"manager"}:
                f:args: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-04-01T02:54:09Z"
  name: helm-controller
  namespace: flux-system
  resourceVersion: "11495675"
  selfLink: /apis/apps/v1/namespaces/flux-system/deployments/helm-controller
  uid: 7c9cc391-8e5f-4088-a8a1-582e785cf17b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helm-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: helm-controller
    spec:
      containers:
      - args:
        - --watch-all-namespaces
        - --log-level=debug
        - --log-encoding=json
        - --enable-leader-election
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: fluxcd/helm-controller:v0.8.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        ports:
        - containerPort: 8080
          name: http-prom
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: temp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: helm-controller
      serviceAccountName: helm-controller
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: temp
status:
  conditions:
  - lastTransitionTime: "2021-04-01T02:50:18Z"
    lastUpdateTime: "2021-04-01T02:50:18Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-04-01T02:50:18Z"
    lastUpdateTime: "2021-04-01T02:54:09Z"
    message: ReplicaSet "helm-controller-689f474f96" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
```

**Comment by sunny0826** [comment] 2021-04-01 02:58
pod log

```shell
$k logs helm-controller-689f474f96-n5rk8
{"level":"info","ts":"2021-04-01T02:57:19.005Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2021-04-01T02:57:19.005Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-04-01T02:57:19.005Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-04-01T02:57:19.005Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-04-01T02:57:19.005Z","logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":"2021-04-01T02:57:19.005Z","logger":"setup","msg":"starting manager"}
I0401 02:57:19.006084       6 leaderelection.go:243] attempting to acquire leader lease flux-system/5b6ca942.fluxcd.io...
{"level":"info","ts":"2021-04-01T02:57:19.106Z","msg":"starting metrics server","path":"/metrics"}
I0401 02:57:35.713610       6 leaderelection.go:253] successfully acquired lease flux-system/5b6ca942.fluxcd.io
{"level":"info","ts":"2021-04-01T02:57:35.713Z","logger":"controller.helmrelease","msg":"Starting EventSource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","source":"kind source: /, Kind="}
{"level":"debug","ts":"2021-04-01T02:57:35.713Z","logger":"events","msg":"Normal","object":{"kind":"ConfigMap","namespace":"flux-system","name":"5b6ca942.fluxcd.io","uid":"662c88a4-7181-461e-87c2-6dfc32f7ecae","apiVersion":"v1","resourceVersion":"11496930"},"reason":"LeaderElection","message":"helm-controller-689f474f96-n5rk8_87fba64e-f7b9-42be-8848-e83d6e1331c1 became leader"}
{"level":"info","ts":"2021-04-01T02:57:35.713Z","logger":"controller.helmrelease","msg":"Starting EventSource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","source":"kind source: /, Kind="}
{"level":"debug","ts":"2021-04-01T02:57:35.713Z","logger":"events","msg":"Normal","object":{"kind":"Lease","namespace":"flux-system","name":"5b6ca942.fluxcd.io","uid":"f85cb33c-2f04-400b-b739-c94ea21fbc84","apiVersion":"coordination.k8s.io/v1","resourceVersion":"11496931"},"reason":"LeaderElection","message":"helm-controller-689f474f96-n5rk8_87fba64e-f7b9-42be-8848-e83d6e1331c1 became leader"}
{"level":"info","ts":"2021-04-01T02:57:35.814Z","logger":"controller.helmrelease","msg":"Starting Controller","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease"}
{"level":"info","ts":"2021-04-01T02:57:35.814Z","logger":"controller.helmrelease","msg":"Starting workers","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","worker count":4}
{"level":"info","ts":"2021-04-01T02:57:48.234Z","logger":"controller.helmrelease","msg":"Stopping workers","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease"}
{"level":"error","ts":"2021-04-01T02:57:48.235Z","msg":"error received after stop sequence was engaged","error":"context canceled","stacktrace":"sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/manager/internal.go:529"}
{"level":"error","ts":"2021-04-01T02:57:48.235Z","msg":"error received after stop sequence was engaged","error":"context canceled","stacktrace":"sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/manager/internal.go:529"}
{"level":"error","ts":"2021-04-01T02:57:48.235Z","msg":"error received after stop sequence was engaged","error":"leader election lost","stacktrace":"sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/manager/internal.go:529"}
```

**Comment by sunny0826** [comment] 2021-04-01 02:59
pod describe

```shell
k describe pod helm-controller-689f474f96-n5rk8
Name:         helm-controller-689f474f96-n5rk8
Namespace:    flux-system
Priority:     0
Node:         cn-beijing.10.129.92.187/10.129.92.187
Start Time:   Thu, 01 Apr 2021 10:54:09 +0800
Labels:       app=helm-controller
              pod-template-hash=689f474f96
Annotations:  kubernetes.io/psp: ack.privileged
              prometheus.io/port: 8080
              prometheus.io/scrape: true
Status:       Running
IP:           10.130.71.187
IPs:
  IP:           10.130.71.187
Controlled By:  ReplicaSet/helm-controller-689f474f96
Containers:
  manager:
    Container ID:  docker://58de242b95c88787027e84345f1d1c7135aa9c07a19da52e123d6111804cebef
    Image:         fluxcd/helm-controller:v0.8.0
    Image ID:      docker-pullable://fluxcd/helm-controller@sha256:e31eca0551dd6dce5591ded0b1946e6fbb1a825e6864e7a546b03b5a0bd69b5b
    Ports:         8080/TCP, 9440/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --watch-all-namespaces
      --log-level=debug
      --log-encoding=json
      --enable-leader-election
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 01 Apr 2021 10:57:18 +0800
      Finished:     Thu, 01 Apr 2021 10:57:48 +0800
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   64Mi
    Liveness:   http-get http://:healthz/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:healthz/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      RUNTIME_NAMESPACE:  flux-system (v1:metadata.namespace)
    Mounts:
      /tmp from temp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from helm-controller-token-5fc96 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  temp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  helm-controller-token-5fc96:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  helm-controller-token-5fc96
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       4m32s                  default-scheduler  Successfully assigned flux-system/helm-controller-689f474f96-n5rk8 to cn-beijing.10.129.92.187
  Normal   AllocIPSucceed  4m31s                  terway-daemon      Alloc IP 10.130.71.187/18 for Pod
  Normal   Pulled          3m34s (x3 over 4m30s)  kubelet            Container image "fluxcd/helm-controller:v0.8.0" already present on machine
  Normal   Created         3m34s (x3 over 4m30s)  kubelet            Created container manager
  Normal   Started         3m34s (x3 over 4m30s)  kubelet            Started container manager
  Normal   Killing         3m34s (x2 over 4m4s)   kubelet            Container manager failed liveness probe, will be restarted
  Warning  Unhealthy       3m25s (x7 over 4m25s)  kubelet            Readiness probe failed: Get http://10.130.71.187:9440/readyz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy       3m24s (x7 over 4m24s)  kubelet            Liveness probe failed: Get http://10.130.71.187:9440/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by barnettZQG** [comment] 2022-04-19 02:35
@sunny0826 This issue context has changed and I will close this issue.

**Closed by barnettZQG** 2022-04-19 02:35 UTC
Labels: type/bug
