### ISSUE TITLE
[BUG] vela exec 

### ISSUE THREAD

**Issue by szihai** [oam-dev/kubevela#589] opened 2020-11-12 21:51 UTC
**Describe the bug**
I run a command 
vela exec testapp -- printenv | grep KUBE
and it hangs without breaking the line.

**To Reproduce**
Use vela up to start any sample app.
Run `vela exec <yourappname> -- printenv`  and it works.
Then add a pipe `vela exec <yourappname> -- printenv | grep KUBE`. **Vela hangs**.
If you use `kubectl exec` with the same command, it works fine.

**Comment by hongchaodeng** [comment] 2020-11-17 19:32
I couldn't reproduce it.

**Comment by szihai** [comment] 2020-11-17 21:21
I'm attaching the screenshot of the situation I encountered.
[bug589.zip](https://github.com/oam-dev/kubevela/files/5556266/bug589.zip)

**Comment by wonderflow** [comment] 2020-12-30 07:35
closing as I can't repoduce either. @szihai  please try the new version and feel free to reopen if it still exists.

**Closed by wonderflow** 2020-12-30 07:35 UTC
