### ISSUE TITLE
[BUG] The vela app delete does not delete the components

### ISSUE THREAD

**Issue by ryanzhang-oss** [oam-dev/kubevela#357] opened 2020-10-08 00:19 UTC
**Describe the bug**
The vela app delete does not delete the components

**To Reproduce**
Follow the README in https://github.com/oam-dev/kubevela/README
 
**Expected behavior**

**Screenshots**
```
~/workspace/oam/kubevela (improvement) $ vela app delete myapp
Deleting Application "myapp"
delete apps succeed myapp from demo
~/workspace/oam/kubevela (improvement) $ kc -n demo get all
NAME                            READY   STATUS        RESTARTS   AGE
pod/cm-acme-http-solver-92b6f   0/1     Terminating   0          41m
pod/db-5b4d656878-x2lkv         1/1     Running       0          47m
pod/mycomp-54b57c8bb4-q6bpk     1/1     Running       0          47m

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/db       1/1     1            1           47m
deployment.apps/mycomp   1/1     1            1           47m

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/db-5b4d656878       1         1         1       47m
replicaset.apps/mycomp-54b57c8bb4   1         1         1       47m
```

One can see there somehow there is both deployment and replica set in the system that can't be deleted.

**Cluster information**
Minikube 1.17.1

**Comment by wonderflow** [comment] 2020-10-08 03:13
Can you show if there is still an ApplicationConfiguration named `myapp` there?

**Comment by wonderflow** [comment] 2020-10-29 09:48
closing as I can't reproduce it

**Closed by wonderflow** 2020-10-29 09:48 UTC
